from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy.orm import Session


def run_security_analyzer(
    db: Session,
    *,
    tenant_id: UUID,
    cloud_account_id: UUID,
    sync_run_id: UUID,
) -> dict[str, Any]:
    # Phase-1 scaffold: security recommendations are generated by the existing recommendation_service.
    # This module exists so we can split the legacy analyzer monolith into deterministic domain analyzers later.
    _ = (db, tenant_id, cloud_account_id, sync_run_id)
    return {"analyzer": "security", "status": "stub"}

